"""Initial migration - create flood_data tables

Revision ID: 6643d7a3d4a9
Revises: 
Create Date: 2025-11-09 14:41:57.870993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6643d7a3d4a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flood_data_collections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('data_source', sa.String(length=20), nullable=False, comment="Source: 'real' or 'simulated'"),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('river_stations_count', sa.Integer(), nullable=True),
    sa.Column('weather_data_available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_collected_at_desc', 'flood_data_collections', [sa.literal_column('collected_at DESC')], unique=False)
    op.create_index('idx_success_collected_at', 'flood_data_collections', ['success', 'collected_at'], unique=False)
    op.create_index(op.f('ix_flood_data_collections_collected_at'), 'flood_data_collections', ['collected_at'], unique=False)
    op.create_index(op.f('ix_flood_data_collections_id'), 'flood_data_collections', ['id'], unique=False)
    op.create_table('river_levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('station_name', sa.String(length=100), nullable=False),
    sa.Column('station_id', sa.String(length=50), nullable=True),
    sa.Column('water_level', sa.Float(), nullable=False, comment='Water level in meters'),
    sa.Column('risk_level', sa.String(length=20), nullable=False, comment='NORMAL, ALERT, ALARM, or CRITICAL'),
    sa.Column('alert_level', sa.Float(), nullable=True, comment='Alert threshold in meters'),
    sa.Column('alarm_level', sa.Float(), nullable=True, comment='Alarm threshold in meters'),
    sa.Column('critical_level', sa.Float(), nullable=True, comment='Critical threshold in meters'),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('data_source', sa.String(length=50), nullable=True, comment='PAGASA station or simulated'),
    sa.ForeignKeyConstraint(['collection_id'], ['flood_data_collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_collection_station', 'river_levels', ['collection_id', 'station_name'], unique=False)
    op.create_index('idx_risk_level', 'river_levels', ['risk_level'], unique=False)
    op.create_index('idx_station_recorded_at', 'river_levels', ['station_name', sa.literal_column('recorded_at DESC')], unique=False)
    op.create_index(op.f('ix_river_levels_collection_id'), 'river_levels', ['collection_id'], unique=False)
    op.create_index(op.f('ix_river_levels_station_name'), 'river_levels', ['station_name'], unique=False)
    op.create_table('weather_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('rainfall_1h', sa.Float(), nullable=True, comment='Rainfall in last hour (mm)'),
    sa.Column('rainfall_3h', sa.Float(), nullable=True, comment='Rainfall in last 3 hours (mm)'),
    sa.Column('rainfall_24h_forecast', sa.Float(), nullable=True, comment='24-hour rainfall forecast (mm)'),
    sa.Column('intensity', sa.String(length=20), nullable=True, comment='Light, Moderate, Heavy, or Intense'),
    sa.Column('intensity_category', sa.String(length=50), nullable=True, comment='PAGASA classification'),
    sa.Column('temperature', sa.Float(), nullable=True, comment='Temperature in Celsius'),
    sa.Column('humidity', sa.Float(), nullable=True, comment='Humidity percentage'),
    sa.Column('pressure', sa.Float(), nullable=True, comment='Atmospheric pressure (hPa)'),
    sa.Column('weather_main', sa.String(length=50), nullable=True, comment='Main weather condition'),
    sa.Column('weather_description', sa.String(length=100), nullable=True, comment='Detailed description'),
    sa.Column('wind_speed', sa.Float(), nullable=True, comment='Wind speed (m/s)'),
    sa.Column('wind_direction', sa.Float(), nullable=True, comment='Wind direction (degrees)'),
    sa.Column('location_name', sa.String(length=100), nullable=True, comment='Location name'),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('data_source', sa.String(length=50), nullable=True, comment='API source'),
    sa.ForeignKeyConstraint(['collection_id'], ['flood_data_collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_intensity', 'weather_data', ['intensity'], unique=False)
    op.create_index('idx_recorded_at', 'weather_data', [sa.literal_column('recorded_at DESC')], unique=False)
    op.create_index(op.f('ix_weather_data_collection_id'), 'weather_data', ['collection_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_data_collection_id'), table_name='weather_data')
    op.drop_index('idx_recorded_at', table_name='weather_data')
    op.drop_index('idx_intensity', table_name='weather_data')
    op.drop_table('weather_data')
    op.drop_index(op.f('ix_river_levels_station_name'), table_name='river_levels')
    op.drop_index(op.f('ix_river_levels_collection_id'), table_name='river_levels')
    op.drop_index('idx_station_recorded_at', table_name='river_levels')
    op.drop_index('idx_risk_level', table_name='river_levels')
    op.drop_index('idx_collection_station', table_name='river_levels')
    op.drop_table('river_levels')
    op.drop_index(op.f('ix_flood_data_collections_id'), table_name='flood_data_collections')
    op.drop_index(op.f('ix_flood_data_collections_collected_at'), table_name='flood_data_collections')
    op.drop_index('idx_success_collected_at', table_name='flood_data_collections')
    op.drop_index('idx_collected_at_desc', table_name='flood_data_collections')
    op.drop_table('flood_data_collections')
    # ### end Alembic commands ###
